"R Script for the visualisation of single proteins during the intervention in plasma samples.
Output: Line plots, containing PRO and CTR"

load libraries
```{r}
install.packages("readxl") 
library(readxl)
install.packages("dplyr") 
library(dplyr)
library(tidyr)
library(ggplot2)
```
Load data from excel
```{r}
data <- read_xlsx("/Users/majaewen/Documents/Uni/6_Semester/Daten/Proteomics/ProteinData_with_pValues_Renamed.xlsx")
head(data)
```

```{r}
data_skipped_PRO <- data[seq(2, nrow(data), by = 2), ] 
data_skipped_CTR <- data[seq(1, nrow(data), by = 2), ]

data_CTR <- data_skipped_CTR %>% select(-starts_with("Profi")) 
data_CTR <- subset(data_CTR, select = -c(p.adj, p, Group, ID, Protein_name))
data_PRO <- data_skipped_PRO %>% select(-starts_with("Control"))
data_PRO <- subset(data_PRO, select = -c(p.adj, p, Group, ID, Protein_name))

head(data_CTR)
head(data_PRO)
```
###PRO###
```{r}
column_info <- data.frame(
  original_name = colnames(data_PRO)
) %>%
  mutate(
    Proband = stringr::str_extract(original_name, "(P|SJ)\\d+"),
    Timepoint = stringr::str_extract(original_name, "T\\d+"),
    Proband_num = as.numeric(stringr::str_remove(Proband, "(P|SJ)")),
    Timepoint_num = as.numeric(stringr::str_remove(Timepoint, "T"))
  ) %>%
  arrange(Timepoint_num, Proband_num)

df_sorted_PRO <- data_PRO[, column_info$original_name]

```

Enter target protein!
```{r}
protein <- "DAZAP1" #here!
protein_row <- df_sorted_PRO %>% filter(Gene_name == protein)
if (nrow(protein_row) == 0) stop("Protein not found!")
```

```{r}
long_df <- protein_row %>%
  pivot_longer(
    cols = -Gene_name,
    names_to = "Sample",
    values_to = "Intensity"
  ) %>%
  separate(Sample, into = c("Type", "Proband", "Timepoint"), sep = "_")
```


Calculate mean and standard deviation
```{r}
long_df <- long_df %>%
  mutate(Intensity = as.numeric(Intensity)) 

summary_df <- long_df %>%
  group_by(Timepoint) %>%
  summarise(
    mean_z = mean(Intensity, na.rm = TRUE),
    sd_intensity = sd(Intensity, na.rm = TRUE),
    n = n(),
    sem_z = sd_intensity / sqrt(n)
  )
```


```{r}
ggplot(summary_df, aes(x = Timepoint, y = mean_z, group = 1)) +
  geom_ribbon(aes(ymin = mean_z - sem_z, ymax = mean_z + sem_z), fill = "green", alpha = 0.2) +
  geom_line(color = "darkgreen", size = 1.2) +
  geom_point(color = "darkgreen", size = 2) +
  theme_minimal(base_size = 14) +
  labs(
    title = paste(protein),
    y = "Intensity (mean ± SEM)",
    x = "Timepoint"
  )
```

###CTR###
```{r}
column_info <- data.frame(
  original_name = colnames(data_CTR)
) %>%
  mutate(
    Proband = stringr::str_extract(original_name, "(C|P|SJ)\\d+"),
    Timepoint = stringr::str_extract(original_name, "T\\d+"),
    Proband_num = as.numeric(stringr::str_remove(Proband, "(C|P|SJ)")),
    Timepoint_num = as.numeric(stringr::str_remove(Timepoint, "T"))
  ) %>%
  arrange(Timepoint_num, Proband_num)

df_sorted_CTR <- data_CTR[, column_info$original_name]

```

```{r}
protein_row_CTR <- df_sorted_CTR %>% filter(Gene_name == protein)
if (nrow(protein_row_CTR) == 0) stop("Protein not found!")
```

```{r}
long_df_CTR <- protein_row_CTR %>%
  pivot_longer(
    cols = -Gene_name,
    names_to = "Sample",
    values_to = "Intensity"
  ) %>%
  separate(Sample, into = c("Type", "Proband", "Timepoint"), sep = "_")
```


Calculate mean and standard deviation
```{r}
long_df_CTR <- long_df_CTR %>%
  mutate(Intensity = as.numeric(Intensity)) 

summary_df_CTR <- long_df_CTR %>%
  group_by(Timepoint) %>%
  summarise(
    mean_z = mean(Intensity, na.rm = TRUE),
    sd_intensity = sd(Intensity, na.rm = TRUE),
    n = n(),
    sem_z = sd_intensity / sqrt(n)
  )
```


```{r}
ggplot(summary_df_CTR, aes(x = Timepoint, y = mean_z, group = 1)) +
  geom_ribbon(aes(ymin = mean_z - sem_z, ymax = mean_z + sem_z), fill = "green", alpha = 0.2) +
  geom_line(color = "darkgreen", size = 1.2) +
  geom_point(color = "darkgreen", size = 2) +
  theme_minimal(base_size = 14) +
  labs(
    title = paste(protein),
    y = "Intensity (mean ± SEM)",
    x = "Timepoint"
  )
```

Merge both plots
```{r}
summary_df_CTR$group <- "CTR"

summary_df$group <- "PRO"

summary_combined <- bind_rows (summary_df_CTR, summary_df)
```

```{r}
ggplot(summary_combined, aes(x = Timepoint, y = mean_z, color = group, group = group)) +
  geom_line(size = 1.2) +
  geom_point(size = 2) +
  scale_color_manual(values = c("CTR" = "blue", "PRO" = "red")) +
  scale_fill_manual(values = c("CTR" = "blue", "PRO" = "red")) +
  geom_ribbon(aes(ymin = mean_z - sem_z, ymax = mean_z + sem_z, fill = group), alpha = 0.2, color = NA) +
  theme_minimal(base_size = 14) +
  labs(
    title = paste(protein),
    x = "timepoint",
    y = "Intensity (mean ± SEM)",
    color = "group",
    fill = "group"
  )
```